let data_specialty_class = [
  {
    id: 1,
    specialty_name: 'Công nghệ thông tin',
    subjects: [
      {
        id: 1,
        subject_name: 'Tiếng anh công nghệ thông tin',
        specialty_id: 1,
        credit_id: 1,
      },
      {
        id: 3,
        subject_name: 'Tiếng anh công nghệ thông tin 2',
        specialty_id: 1,
        credit_id: 2,
      },
    ],
  },
  {
    id: 2,
    specialty_name: 'Kỹ thuật phần mềm',
    subjects: [
      {
        id: 2,
        subject_name: 'Lập trình web bằng PHP',
        specialty_id: 2,
        credit_id: 1,
      },
    ],
  },
]

let data_class_subject = [
  {
    class_id: 'PHP007',
    start_date: 'Fri May 20 2022 10:43:50 GMT+0700',
    max_number_students: 70,
    current_number_students: 0,
    user_id: 3,
    schedules: '[{"day":1,"lessons":[6,7,8,9]}]',
    subject_id: 2,
    teacher: {
      user_id: 3,
      specialty_id: 2,
      user: {
        user_id: 3,
        full_name: 'Hoang Tuan Hieu',
        email: 'tranducha2@gmail.com',
        date_of_birth: '1996-01-01',
        gender: 'fe-male',
        address: 'Bac Ninh',
        avatar: '',
        username: 'hoangtuanhieu',
        role_id: 'r2',
      },
    },
    subject: {
      id: 1,
      subject_name: 'Tiếng anh công nghệ thông tin',
      image: 'https://files.fullstack.edu.vn/f8-prod/banners/Banner_web_ReactJS.png',
      description:
        'Với kiến thức ong đốt đặc trưng đã làm nên thương hiệu của thầy Nguyễn Trung Phú. Sau khi học xong thì không ngán bất cứ một ai, cứ đến là đón',
      specialty_id: 1,
      credit_id: 1,
      background_color: 'linear-gradient(to right, #667db6, #0082c8, #0082c8, #667db6)',
    },
  },
  {
    class_id: 'PHP008',
    start_date: 'Fri May 20 2022 10:47:44 GMT+0700',
    max_number_students: 70,
    current_number_students: 0,
    user_id: 3,
    schedules: '[{"day":4,"lessons":[6,7,8,9]}]',
    subject_id: 2,
    teacher: {
      user_id: 3,
      specialty_id: 2,
      user: {
        user_id: 3,
        full_name: 'Hoang Tuan Hieu',
        email: 'tranducha2@gmail.com',
        date_of_birth: '1996-01-01',
        gender: 'fe-male',
        address: 'Bac Ninh',
        avatar: '',
        username: 'hoangtuanhieu',
        role_id: 'r2',
      },
    },
    subject: {
      id: 3,
      subject_name: 'Tiếng anh công nghệ thông tin 2',
      image: 'https://files.fullstack.edu.vn/f8-prod/banners/Banner_03_youtube.png',
      description:
        'Với kiến thức ong đốt đặc trưng đã làm nên thương hiệu của thầy Nguyễn Trung Phú. Sau khi học xong thì không ngán bất cứ một ai, cứ đến là đón',
      specialty_id: 1,
      credit_id: 2,
      background_color: 'linear-gradient(to right, #fc4a1a, #f7b733)',
    },
  },
  {
    class_id: 'PHP007',
    start_date: 'Fri May 20 2022 10:43:50 GMT+0700',
    max_number_students: 70,
    current_number_students: 0,
    user_id: 3,
    schedules: '[{"day":1,"lessons":[6,7,8,9]}]',
    subject_id: 2,
    teacher: {
      user_id: 3,
      specialty_id: 2,
      user: {
        user_id: 3,
        full_name: 'Hoang Tuan Hieu',
        email: 'tranducha2@gmail.com',
        date_of_birth: '1996-01-01',
        gender: 'fe-male',
        address: 'Bac Ninh',
        avatar: '',
        username: 'hoangtuanhieu',
        role_id: 'r2',
      },
    },
    subject: {
      id: 1,
      subject_name: 'Tiếng anh công nghệ thông tin',
      image: 'https://files.fullstack.edu.vn/f8-prod/banners/Banner_web_ReactJS.png',
      description:
        'Với kiến thức ong đốt đặc trưng đã làm nên thương hiệu của thầy Nguyễn Trung Phú. Sau khi học xong thì không ngán bất cứ một ai, cứ đến là đón',
      specialty_id: 1,
      credit_id: 1,
      background_color: 'linear-gradient(to right, #667db6, #0082c8, #0082c8, #667db6)',
    },
  },
  {
    class_id: 'PHP008',
    start_date: 'Fri May 20 2022 10:47:44 GMT+0700',
    max_number_students: 70,
    current_number_students: 0,
    user_id: 3,
    schedules: '[{"day":4,"lessons":[6,7,8,9]}]',
    subject_id: 2,
    teacher: {
      user_id: 3,
      specialty_id: 2,
      user: {
        user_id: 3,
        full_name: 'Hoang Tuan Hieu',
        email: 'tranducha2@gmail.com',
        date_of_birth: '1996-01-01',
        gender: 'fe-male',
        address: 'Bac Ninh',
        avatar: '',
        username: 'hoangtuanhieu',
        role_id: 'r2',
      },
    },
    subject: {
      id: 3,
      subject_name: 'Tiếng anh công nghệ thông tin 2',
      image: 'https://files.fullstack.edu.vn/f8-prod/banners/Banner_03_youtube.png',
      description:
        'Với kiến thức ong đốt đặc trưng đã làm nên thương hiệu của thầy Nguyễn Trung Phú. Sau khi học xong thì không ngán bất cứ một ai, cứ đến là đón',
      specialty_id: 1,
      credit_id: 2,
      background_color: 'linear-gradient(to right, #fc4a1a, #f7b733)',
    },
  },
]
